// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_financial_system.Context;

#nullable disable

namespace Project_financial_system.Migrations
{
    [DbContext(typeof(FinancialContext))]
    [Migration("20240622174239_AddedCustomersAndAddress")]
    partial class AddedCustomersAndAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project_financial_system.Models.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdAddress");

                    b.ToTable("Adrdess");
                });

            modelBuilder.Entity("Project_financial_system.Models.Domain.Customer", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCustomer"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("IdCustomer");

                    b.HasIndex("IdAddress");

                    b.ToTable("Customer", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Project_financial_system.Models.Domain.CompanyCustomer", b =>
                {
                    b.HasBaseType("Project_financial_system.Models.Domain.Customer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KRS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Company_Customer", (string)null);
                });

            modelBuilder.Entity("Project_financial_system.Models.Domain.IndividualCustomer", b =>
                {
                    b.HasBaseType("Project_financial_system.Models.Domain.Customer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.ToTable("Individual_Customer", (string)null);
                });

            modelBuilder.Entity("Project_financial_system.Models.Domain.Customer", b =>
                {
                    b.HasOne("Project_financial_system.Models.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Project_financial_system.Models.Domain.CompanyCustomer", b =>
                {
                    b.HasOne("Project_financial_system.Models.Domain.Customer", null)
                        .WithOne()
                        .HasForeignKey("Project_financial_system.Models.Domain.CompanyCustomer", "IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_financial_system.Models.Domain.IndividualCustomer", b =>
                {
                    b.HasOne("Project_financial_system.Models.Domain.Customer", null)
                        .WithOne()
                        .HasForeignKey("Project_financial_system.Models.Domain.IndividualCustomer", "IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_financial_system.Models.Address", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
